### PR TITLE
Cache creation of a `Timer`

### PR DESCRIPTION
**Pull request by alexcrichton**
Each timer created spawns a new thread! By only having one for the `App`
it means we're not spawning a thread-per-request.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I was seeing some very surprising numbers on linux (3k req/s for sync and 20k for async) so I wanted to investigate! Turns out this is a major source of slowdown on OSX.

**Comment by rkusa** [comment]
Cool, this is exactly the kind of feedback I was looking for, thanks! I just compared `thread:sleep` with `sleep.wait()` to make sure we still have a fair comparison. However when taking a look at the results I saw that for the `20ms` delay case, the Tokio timer results cannot be trusted:

```
Summary:
  Total:	0.9398 secs
  Slowest:	0.0652 secs
  Fastest:	0.0001 secs
  Average:	0.0091 secs
  Requests/sec:	10640.3354
```

The **Fastest** request cannot be `0.0001 secs`, because it should have a 20ms delay (0.02secs). `thread::sleep` gets this delay correct. This is something I like to look into first, before updating the benchmarks. There is no such issue for the `200ms` case.

**Comment by alexcrichton** [comment]
I wonder if this is a bug in tokio-timer or maybe the usage of tokio-timer? I've personally found `tokio_core::reactor::Timeout` to be more reliable, and with it I get:

```
Summary:
  Total:        7.2211 secs
  Slowest:      0.1003 secs
  Fastest:      0.0219 secs
  Average:      0.0715 secs
  Requests/sec: 1384.8267
```

which looks more expected! Would you like me to push up that version?

**Comment by alexcrichton** [comment]
Eh I wnet ahead and pushed it up

**Comment by rkusa** [comment]
> I wonder if this is a bug in tokio-timer or maybe the usage of tokio-timer?

I think, I am going to create a minimal test case to reproduce this case and fill an issue in the tokio-timer (but probably not before tomorrow).

> Would you like me to push up that version?

Yes, that would be nice! Thanks

**Comment by rkusa** [comment]
Thanks again! I'll update the results as soon as possible (which will be tomorrow for some of them)

**Comment by rkusa** [comment]
> on linux (3k req/s for sync and 20k for async) 

Interestingly, on macOS, I only get different results due to the issue with `tokio-timer`. How does the 20ms delay case of sync with 100 threads compare to the async one on Linux now?

**Comment by rkusa** [comment]
> I wonder if this is a bug in tokio-timer or maybe the usage of tokio-timer?

I think it was my usage of tokio-timer. The default timer setting has a tick rate of 100ms and the docs state:

> Given the fact that the timer operates in ticks, a timeout can only be as precise as the tick duration. If the tick size is 100ms, any timeout request that falls within that 100ms slot will be triggered at the same time.

**Pull request merged**
